### PR TITLE
Doing tasks

### PR DESCRIPTION
**Pull request by olebohem**
Some minor things caused some of the tasks to take longer time to solve for me than it should.

Proposing some minor changes that might make it easier for the participants.

### CODE REVIEW

**Comment by eoaksnes** [comment]
Change task 4 solution: 

Then the response should contain
    """
    {
      "hits":{
        "total":2,
        "hits":[
          {
            "_source":{
              "name":"American Bacon"
            }
          },
          {
            "_source":{
              "name":"Classic American"
            }
          }
        ]
      }
    }

I guess this is wrong? Should only contain pizzas with Meatballs in the name.

**Comment by eoaksnes** [comment]
The rest of the changes look very good! Awesome :)

**Comment by olebohem** [comment]
Good catch. Forgot to add that part:) Have updated the commit.

**Comment by eoaksnes** [comment]
Awesome!

**Pull request merged**
